### ISSUE TITLE
Flow not working

### ISSUE THREAD

**Issue by FrankX0** [scambo00/HoneywellLyricAPInodeRed#2]
Still not working.
Trying to dig deeper, hope someone gives a hand (@scambo00 , @donavanbecker)

First of all: the flow seems to be written for a Node Red installation on BlueMix.
context.global.BlueMixUrlBase is not defined anywhere.

I am running on a Local Raspberry Pi.
My biggest issue seems to be the redirect-URL.

To be continued....

**Comment by scambo00** [comment]
This was used to integrate the Honeywell Lyric Thermostat into a project called WinkNodeRed.  WinkNodeRed is no longer supported and without it this will not work.  I have been working on a stand alone nodered flow for the Honeywell Lyric API and if you are interested I will post that code to its own GitHub repo

**Comment by FrankX0** [comment]
That would be great!

**Comment by donavanbecker** [comment]
> This was used to integrate the Honeywell Lyric Thermostat into a project called WinkNodeRed. WinkNodeRed is no longer supported and without it this will not work. I have been working on a stand alone nodered flow for the Honeywell Lyric API and if you are interested I will post that code to its own GitHub repo

Thanks! I would definitely use that!

**Comment by scambo00** [comment]
Can you tell me how this would be used?  I can try and put some effort into making it work to meet your needs.  I seem to have a little time on my hands lately :) so i'll work on this over the next couple of days.

**Comment by donavanbecker** [comment]
I was actually think of typing it into HomeKit with the HomeKit nodes that are available.

**Comment by FrankX0** [comment]
For me it would be good enough to be able to set and get the thermostat data like in your current flow. I guess this will make it possible to connect to e.g. MQTT or even HomeKit?

**Comment by scambo00** [comment]
Do you have more than one Lyric Device?  I don't have or use HomeKit so I can't help there.

**Comment by donavanbecker** [comment]
I only have 1.

**Comment by FrankX0** [comment]
Hi @donavanbecker 
Why are you looking for integration of the Lyric thermostat in HomeKit through Node Red: it is already supported by HomeKit directly.
Secondly, if needed, you can use the HomeKit support from [Node Red](https://flows.nodered.org/node/node-red-contrib-homekit). No need to implement this again.

So as long as there is a way to get and set the temperature, you can integrate this with e.g. MQTT and HomeKit.

**Comment by donavanbecker** [comment]
@FrankX0 not all lyric/Honeywell home thermostats have HomeKit.

**Comment by donavanbecker** [comment]
> Do you have more than one Lyric Device?  I don't have or use HomeKit so I can't help there.

@scambo00 thanks for creating the flow!

**Comment by scambo00** [comment]
Use the latest code from this https://github.com/scambo00/NodeRed-Honeywell-Lyric-API
As of 4/2/2020

**Comment by FrankX0** [comment]
Brilliant!
Thank you so much!

One (small) remark: when Node Red is run locally, you should also add the port number to the base url.

Thanks again for you effort!
